import {
  AlertTriangle,
  ArrowDown,
  ArrowUp,
  BarChart,
  Bell,
  Calendar,
  ChartNoAxesCombined,
  Check,
  CheckIcon,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  ChevronsUpDownIcon,
  CircleDollarSign,
  CircleUser,
  Columns,
  CreditCard,
  CrossIcon,
  DatabaseBackup,
  Download,
  Eye,
  EyeOff,
  Facebook,
  FileSpreadsheet,
  Filter,
  GitGraphIcon,
  HandCoins,
  Home,
  Image,
  Instagram,
  Lightbulb,
  Linkedin,
  List,
  Loader2,
  LoaderIcon,
  LockKeyhole,
  LogOut,
  Menu,
  Moon,
  Pencil,
  PiggyBank,
  Plus,
  PlusCircle,
  PlusCircleIcon,
  PlusIcon,
  RefreshCw,
  Repeat,
  Search,
  Settings,
  SlidersHorizontal,
  Sun,
  Trash,
  TrendingDown,
  TrendingUp,
  Twitter,
  User,
  UserCheck,
  UserPlus,
  Users,
  UserX,
  View,
  WalletCards,
  X,
} from 'lucide-react'

export const Icons = {
  add: PlusIcon,
  addCircle: PlusCircle,
  addCircleIcon: PlusCircleIcon,
  addUser: UserPlus,
  arrowDown: ArrowDown,
  arrowUp: ArrowUp,
  backup: DatabaseBackup,
  barChart: BarChart,
  calendar: Calendar,
  check: Check,
  checkIcon: CheckIcon,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  chevronsUpDown: ChevronsUpDown,
  chevronsUpDownIcon: ChevronsUpDownIcon,
  columns: Columns,
  costumers: Users,
  creditCard: CreditCard,
  cross: CrossIcon,
  csv: FileSpreadsheet,
  download: Download,
  edit: Pencil,
  eye: Eye,
  errorTriangle: AlertTriangle,
  excel: FileSpreadsheet,
  facebook: Facebook,
  filter: Filter,
  graphChart: ChartNoAxesCombined,
  handCoins: HandCoins,
  hide: EyeOff,
  home: Home,
  instagram: Instagram,
  installments: WalletCards,
  lightbulb: Lightbulb,
  linkedin: Linkedin,
  list: List,
  loader: Loader2,
  logoIcon: GitGraphIcon,
  logout: LogOut,
  menu: Menu,
  money: CircleDollarSign,
  moon: Moon,
  new: Plus,
  notifications: Bell,
  piggyBank: PiggyBank,
  placeholder: Image,
  repeat: Repeat,
  refresh: RefreshCw,
  search: Search,
  security: LockKeyhole,
  settings: Settings,
  settingsHorizontal: SlidersHorizontal,
  spinner: LoaderIcon,
  sun: Sun,
  trash: Trash,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  twitter: Twitter,
  updown: ChevronsUpDown,
  user: CircleUser,
  user2: User,
  user_active: UserCheck,
  user_inactive: UserX,
  view: View,
  x: X,
}
